- name: Prepare Lab ENV for Compliance Demo
  hosts: cisco_only
  gather_facts: false

  tasks:
    - name: Remove STIG configs and add ntp
      cisco.ios.config:
        commands:
          - no banner login
          - ntp server 192.0.2.0
          - ntp server 192.0.2.1
      ignore_errors: yes

- name: Prepare Lab ENV for Compliance Demo
  hosts: rtr4
  gather_facts: false

  tasks:
    - name: Remove rtr4 configs
      cisco.ios.config:
        commands:
          - no interface Loopback0
          - no interface Tunnel0
          - no router ospf 1
          - no ntp server 1.1.1.1
          - no ntp server 2.2.2.2
          - no ntp server 192.0.2.0
          - no ntp server 192.0.2.1
          - no snmp-server community CommunityString1 RO
          - no snmp-server community CommunityString2 RO

      ignore_errors: yes

- name: Prepare Lab ENV for Compliance Demo
  hosts: rtr1
  gather_facts: false

  tasks:
    - name: Add rtr3 network to BGP
      cisco.ios.ios_bgp_address_family:
        config:
          as_number: 65000
          address_family:
            - afi: ipv4
              network:
                - address: 192.168.3.3
                  mask: 255.255.255.255
        state: merged

- name: Prepare Lab ENV for Compliance Demo
  hosts: rtr2
  gather_facts: false

  tasks:
    - name: Remove rtr4 network from BGP
      cisco.ios.ios_config:
        lines:
          - no network 192.168.4.4 mask 255.255.255.255
        parents:
          - router bgp 65001
          - address-family ipv4

- name: Prepare IPSLA on rtr3
  hosts: rtr3
  gather_facts: false

  vars:
    - router_id: "192.168.4.4"
    - id: 10

  tasks:
    - name: configure IPSLA
      ansible.netcommon.cli_config:
        config: "{{ lookup('template','../templates/ipsla.j2' ) }}"
