---
# This task will backup the current running configuration

- name: retreive configuration from backup-server to execution environment
  ansible.builtin.fetch:
    src: "/home/ec2-user/intended_config/{{ rtr_item }}.cfg"
    dest: "/tmp/{{ rtr_item }}.cfg"
    flat: true
  delegate_to: backup-server
  when: inventory_hostname in groups['backup-servers']
  loop: "{{ rtrs }}"
  loop_control:
    loop_var: rtr_item

- name: Diff against cisco ios configuration
  cisco.ios.config:
    intended_config: "{{ lookup('file', '/tmp/{{ rtrs_item }}.cfg') }}"
    diff_against: intended
  when: inventory_hostname  == rtrs_item 
  loop: "{{ rtrs }}"
  loop_control:
    loop_var: rtrs_item

- name: Fail when Changed for Notifications
  cisco.ios.config:
    intended_config: "{{ lookup('file', '/tmp/{{ rtrs_item }}.cfg') }}"
    diff_against: intended
  when: inventory_hostname  == rtrs_item 
  loop: "{{ rtrs }}"
  loop_control:
    loop_var: rtrs_item
  register: result
  failed_when: result.changed




