---
- name: Health Check to validate configuration and connectivity between rtr3 and new router
  hosts: 
  - cisco_only
  - backup-servers
  gather_facts: false
  vars_files:
    - "../vars/rtrs.yml"

  tasks:
  - name: load validate role
    include_role:
      name: ../roles/validate

  
    