---
- name: Build IOS inventory report
  hosts: backup-servers,cisco_only
  gather_facts: False

  vars:
    desired_ios_version: "17.03.05"
    file_path: /var/www/html/index.html

  tasks:
    - name: gathering IOS facts
      when: "'cisco_only' in group_names"
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: all
      register: all_facts

    - name: IOS Parsed Commands
      when: "'cisco_only' in group_names"
      ansible.utils.cli_parse:
        command: "show interface g1"

        parser:
          name: ansible.netcommon.pyats
      register: structured

    - name: create HTML report
      when: "'backup-servers' in group_names"
      template:
        src: ../templates/report-ios.j2
        dest: "{{ file_path }}"
      ignore_errors: yes
